### ISSUE TITLE
failed to install CRD crds/tenant-crd.yaml

### ISSUE THREAD

**Issue by s3uzz** [liqotech/liqo#842]
#### What happened:
```
[PRE-FLIGHT] [KUBECTL] Kubectl correctly found
[PRE-FLIGHT] [KUBECTL] Using KUBECONFIG: /etc/kubernetes/admin.conf
[PRE-FLIGHT] [KUBECTL] Using context: kubernetes-admin@kubernetes
[PRE-FLIGHT] [DOWNLOAD] Using curl to download files
[PRE-FLIGHT] [DOWNLOAD] Downloading Liqo (version: v0.3.0-rc.2)
[PRE-FLIGHT] [DOWNLOAD] Downloading Helm v3.5.3
[INSTALL] [CONFIGURE] Using namespace: liqo
[INSTALL] [CONFIGURE] Cluster name: LiqoCluster1369
[INSTALL] [CONFIGURE] Pod CIDR: 172.23.0.0/16
[INSTALL] [CONFIGURE] Service CIDR: 10.96.0.0/12
[INSTALL] Installing Liqo on your cluster...
[INSTALL] Packaging the chart...
Error: failed to install CRD crds/tenant-crd.yaml: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
[INSTALL] [FATAL] Something went wrong while installing Liqo
```
#### How to reproduce it (as minimally and precisely as possible):
`curl -sL https://get.liqo.io | bash`
#### Anything else we need to know?:
Same result on aarch64 and amd64

#### Environment:
- Liqo version: latest
- Kubernetes version (use `kubectl version`): `Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/arm64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:39:34Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/arm64"}`
- Network plugin and version: Calico latest

**Comment by palexster** [comment]
Hi @uxusoft, thanks for reporting the issue. The problem seems to be related to a legacy version of CRDs in the version of Capsule Liqo is using. We are updating the dependency and keep you posted when it is fixed.

**Comment by palexster** [comment]
Hi @uxusoft, Liqo should work now with the v0.3.0-rc3.

**Comment by palexster** [comment]
Closing since it has been solved by upgrading the capsule version in v0.3

**Comment by isaacdan** [comment]
Hello All,
I still see this issue 
Error: failed to install CRD crds/crd.yaml: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"

My code looks like below:
resource "helm_release" "aad_pod_identity" {

  depends_on = [helm_release.my_repo, helm_release.cis_secrets_repo, null_resource.aks_blob_driver]

  provider   = helm.akshelmconfig

  name       = "aad-pod-identity"

  repository = "https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts"

  chart      = "aad-pod-identity"

  version    = "4.1.7"

  timeout    = 1200



  values = [<<-EOF

azureIdentities:

- name: "${data.azurerm_user_assigned_identity.ingress_identity[0].name}"

  Labels:

        app=atria-helm

        release="${var.deployment_name}"

  type: 0

  resourceID: "${data.azurerm_user_assigned_identity.ingress_identity[0].id}"

  clientID: "${data.azurerm_user_assigned_identity.ingress_identity[0].client_id}"

  binding:

    name: "${data.azurerm_user_assigned_identity.ingress_identity[0].name}-binding"

    selector: "${var.deployment_name}-atria-helm-ingress-nginx"



  rbac:

    allowAccessToSecrets: true

  installCRDs: true

  nmi:

    allowNetworkPluginKubenet: true

  EOF

  ]

**Comment by isaacdan** [comment]
Hi All, I see the error appear again
Error: failed to install CRD crds/crd.yaml: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"

here is my code

resource "helm_release" "aad_pod_identity" {
  count      = var.ext_cert != "letsencrypt" && var.ingress_class == "nginx" ? 1 : 0
  depends_on = [helm_release.my_repo, helm_release.cis_secrets_repo, null_resource.aks_blob_driver]
  provider   = helm.akshelmconfig
  name       = "aad-pod-identity"
  repository = "https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts"
  chart      = "aad-pod-identity"
  version    = "4.1.7"
  timeout    = 1200

  values = [<<-EOF
azureIdentities:
- name: "${data.azurerm_user_assigned_identity.ingress_identity[0].name}"
  Labels:
        app=atria-helm
        release="${var.deployment_name}"
  type: 0
  resourceID: "${data.azurerm_user_assigned_identity.ingress_identity[0].id}"
  clientID: "${data.azurerm_user_assigned_identity.ingress_identity[0].client_id}"
  binding:
    name: "${data.azurerm_user_assigned_identity.ingress_identity[0].name}-binding"
    selector: "${var.deployment_name}-atria-helm-ingress-nginx"

  rbac:
    enabled: true
    allowAccessToSecrets: true
  installCRDs: true
  nmi:
    allowNetworkPluginKubenet: true
  EOF
  ]
}

**Comment by isaacdan** [comment]
here is my code

 resource "helm_release" "aad_pod_identity" {
   count      = var.ext_cert != "letsencrypt" && var.ingress_class == "nginx" ? 1 : 0
   depends_on = [helm_release.my_repo, helm_release.cis_secrets_repo,    null_resource.aks_blob_driver]
   provider   = helm.akshelmconfig
   name       = "aad-pod-identity"
   repository = "https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts"
   chart      = "aad-pod-identity"
   version    = "4.1.7"
   timeout    = 1200

   values = [<<-EOF
 azureIdentities:
 - name: "${data.azurerm_user_assigned_identity.ingress_identity[0].name}"
   Labels:
         app=atria-helm
         release="${var.deployment_name}"
   type: 0
   resourceID: "${data.azurerm_user_assigned_identity.ingress_identity[0].id}"
   clientID: "${data.azurerm_user_assigned_identity.ingress_identity[0].client_id}"
   binding:
     name: "${data.azurerm_user_assigned_identity.ingress_identity[0].name}-binding"
     selector: "${var.deployment_name}-atria-helm-ingress-nginx"

   rbac:
     enabled: true
     allowAccessToSecrets: true
   installCRDs: true
   nmi:
     allowNetworkPluginKubenet: true
   EOF
   ]
 }

**Comment by palexster** [comment]
Hi @isaacdan,

I think you're installing an old version of Liqo. I suggest to install at least v0.3.1. If you still experience troubles, please open a new issue.
